version: "3.8"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=http://localhost
    ports:
      - "83:80"
    networks:
      - auth
networks:
  auth:
    driver: bridge